### ISSUE TITLE
Fixing OD Policy Map Pins

### ISSUE THREAD

**Issue by alyssajdoom** [sunlightlabs/wwc#24]
WWC Website city map pins should be consistent with those on the sunlight local page (include city name, date policy enacted, legal means, policy url, WWC T/F)
![screen shot 2016-06-21 at 10 40 56 am](https://cloud.githubusercontent.com/assets/11963555/16233600/f770a40a-379c-11e6-84b3-85cd99ef3451.png)

@jalbertbowden

**Comment by jalbertbowden** [comment]
what is the sunlight local page?
the pins are actual icons that are overlayed on the map over locations. Is that what you mean? Doesn't seem like it....just want to make sure.
The location data comes in the modals that are exposed when the user clicks on the pin. I think that is what you are talking about, as that is the focal point of the screen shot and the issue content. If so, is that screen shot a correct version?
Either way, the mocks have them styled completely different.....

**Comment by alyssajdoom** [comment]
Here's the Sunlight local page: http://sunlightfoundation.com/policy/local/
which includes our policy map. when you scroll over the city pin, should
include these details:[image: Inline image 2]

On Thu, Jun 23, 2016 at 7:13 PM, albert <notifications@github.com> wrote:

> what is the sunlight local page?
> the pins are actual icons that are overlayed on the map over locations. Is
> that what you mean? Doesn't seem like it....just want to make sure.
> The location data comes in the modals that are exposed when the user
> clicks on the pin. I think that is what you are talking about, as that is
> the focal point of the screen shot and the issue content. If so, is that
> screen shot a correct version?
> Either way, the mocks have them styled completely different.....
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sunlightlabs/wwc/issues/24#issuecomment-228212996>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALaMo_oSPlhwY3ujRX8StkZhKOS7ApRSks5qOxMagaJpZM4I60KP>
> .
>



-- 
Alyssa Doom
Policy Analyst


1818 N Street NW, Suite 300
Washington, DC 20036

[image: Sunlight Foundation] <http://sunlightfoundation.com/> [image:
Sunlight Foundation on Facebook]
<http://www.facebook.com/sunlightfoundation>[image: Sunlight Foundation on
Twitter] <http://twitter.com/sunfoundation>[image: OpenGov on Reddit]
<http://www.reddit.com/r/sunlight> [image: Sunlight Foundation on YouTube]
<http://www.youtube.com/sunlightfoundation>
<http://sunlightfoundation.com/feeds/latest/>

**Comment by jalbertbowden** [comment]
ok....mind trying to upload that second image again?

**Comment by alyssajdoom** [comment]
it was just the same image. didn't load the first time, sorry!

On Thu, Jun 23, 2016 at 7:29 PM, albert <notifications@github.com> wrote:

> ok....mind trying to upload that second image again?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/sunlightlabs/wwc/issues/24#issuecomment-228215443>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALaMox33IyOeWe-1E18qLFqdFJ6nHK9Aks5qOxa9gaJpZM4I60KP>
> .
>



-- 
Alyssa Doom
Policy Analyst


1818 N Street NW, Suite 300
Washington, DC 20036

[image: Sunlight Foundation] <http://sunlightfoundation.com/> [image:
Sunlight Foundation on Facebook]
<http://www.facebook.com/sunlightfoundation>[image: Sunlight Foundation on
Twitter] <http://twitter.com/sunfoundation>[image: OpenGov on Reddit]
<http://www.reddit.com/r/sunlight> [image: Sunlight Foundation on YouTube]
<http://www.youtube.com/sunlightfoundation>
<http://sunlightfoundation.com/feeds/latest/>

**Comment by katduffy** [comment]
just checked the URL of the louisville policy page and it's broken.
 serving 502 from louisville side.

**Comment by jalbertbowden** [comment]
@alyssajdoom the map modals in the mocks only say to show what is being shown. here's a screenshot: 
![wwc-map-modal-comp-screen-shot](https://cloud.githubusercontent.com/assets/46432/16338407/7f93294e-39ea-11e6-90fb-7e79fab50042.png)

**Comment by jalbertbowden** [comment]
@katduffy ok, i thought you were referring to style of it yesterday...looking at louisville's site briefly, and i don't see where it is.
also we don't maintain the geojson...happy to fix it, but not sure if this is in our wheelhouse.
pinging @SLarrick into this

**Comment by alyssajdoom** [comment]
slack me when you're in and we can discuss! Thanks!

On Fri, Jun 24, 2016 at 9:06 AM, albert <notifications@github.com> wrote:

> @katduffy <https://github.com/katduffy> ok, i thought you were referring
> to style of it yesterday...looking at louisville's site briefly, and i
> don't see where it is.
> also we don't maintain the geojson...happy to fix it, but not sure if this
> is in our wheelhouse.
> pinging @SLarrick <https://github.com/SLarrick> into this
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sunlightlabs/wwc/issues/24#issuecomment-228340202>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALaMo6EPcuiCalgDUY3zGQBYg0PPyvQiks5qO9ZUgaJpZM4I60KP>
> .
>



-- 
Alyssa Doom
Policy Analyst


1818 N Street NW, Suite 300
Washington, DC 20036

[image: Sunlight Foundation] <http://sunlightfoundation.com/> [image:
Sunlight Foundation on Facebook]
<http://www.facebook.com/sunlightfoundation>[image: Sunlight Foundation on
Twitter] <http://twitter.com/sunfoundation>[image: OpenGov on Reddit]
<http://www.reddit.com/r/sunlight> [image: Sunlight Foundation on YouTube]
<http://www.youtube.com/sunlightfoundation>
<http://sunlightfoundation.com/feeds/latest/>

**Comment by jalbertbowden** [comment]
just for reference, searching louisville for open data policy doesn't bring up the doc: https://louisvilleky.gov/gsearch/open%2Bdata%2Bpolicy

**Comment by alyssajdoom** [comment]
Hi All,

Here's the link for Louisville's EO.
https://louisvilleky.gov/government/mayor-greg-fischer/read-open-data-executive-order

On Fri, Jun 24, 2016 at 9:40 AM, albert <notifications@github.com> wrote:

> just for reference, searching louisville for open data policy doesn't
> bring up the doc: https://louisvilleky.gov/gsearch/open%2Bdata%2Bpolicy
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sunlightlabs/wwc/issues/24#issuecomment-228348299>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALaMo_7bHLh6m-ulDHg72V67MVtXaYmpks5qO95SgaJpZM4I60KP>
> .
>



-- 
Alyssa Doom
Policy Analyst


1818 N Street NW, Suite 300
Washington, DC 20036

[image: Sunlight Foundation] <http://sunlightfoundation.com/> [image:
Sunlight Foundation on Facebook]
<http://www.facebook.com/sunlightfoundation>[image: Sunlight Foundation on
Twitter] <http://twitter.com/sunfoundation>[image: OpenGov on Reddit]
<http://www.reddit.com/r/sunlight> [image: Sunlight Foundation on YouTube]
<http://www.youtube.com/sunlightfoundation>
<http://sunlightfoundation.com/feeds/latest/>

**Comment by jalbertbowden** [comment]
@alyssajdoom @katduffy Louisville's data policy reference is now pointing to the correct resource.

**Comment by jalbertbowden** [comment]
@alyssajdoom @SLarrick went to implement this today....you're going to have to be specific here. if you look at what is already being showed and what is not, there's not much difference. furthermore, what does the modal will all the information look like? does it look like the mock or does it look like the above screen shot? i mean does it look like the above in the sense of it being a table, not the style (colors, etc.).
also, the integrity and quality of this data is very questionable, so it will have to be curated again, as well as maintained moving forward. I filed an issue in policy's opendata repository regarding this, but just wanted to reiterate.

**Comment by SLarrick** [comment]
@alyssajdoom @jalbertbowden I believe what is being shown now works. You've got the municipality listed, the date, and the legal means is embedded with the link. You can tell from the pin whether it is a WWC or not. I think we are all good here.

**Comment by alyssajdoom** [comment]
👍 thanks for heads up


On Thu, Jul 7, 2016 at 12:18 PM, Stephen Larrick <notifications@github.com>
wrote:

> @alyssajdoom <https://github.com/alyssajdoom> @jalbertbowden
> <https://github.com/jalbertbowden> I believe what is being shown now
> works. You've got the municipality listed, the date, and the legal means is
> embedded with the link. You can tell from the pin whether it is a WWC or
> not. I think we are all good here.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/sunlightlabs/wwc/issues/24#issuecomment-231129931>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALaMo4TfRKCN6VhjxcQzJnF5cT4709ZAks5qTSa7gaJpZM4I60KP>
> .
>



-- 
Alyssa Doom
Policy Analyst


1818 N Street NW, Suite 300
Washington, DC 20036

[image: Sunlight Foundation] <http://sunlightfoundation.com/> [image:
Sunlight Foundation on Facebook]
<http://www.facebook.com/sunlightfoundation>[image: Sunlight Foundation on
Twitter] <http://twitter.com/sunfoundation>[image: OpenGov on Reddit]
<http://www.reddit.com/r/sunlight> [image: Sunlight Foundation on YouTube]
<http://www.youtube.com/sunlightfoundation>
<http://sunlightfoundation.com/feeds/latest/>

**Comment by jalbertbowden** [comment]
ok well if no more comments i'm closing this. feel free to reopen/open new if there's a problem
