### ISSUE TITLE
IMPORTANT - Resources Switched/Mixed Up

### ISSUE THREAD

**Issue by SLarrick** [sunlightlabs/wwc#30]
@jalbertbowden Somehow when design changes were rolled out the resources listed under "Setting Policy Objectives for Broad Appeal" were switched with the resources listed under "Drafting Policy Language" > "Learn from Examples". This issue may be related to #27 

These resources, currently listed under "Setting Policy Objectives for Broad Appeal" should be listed under "Drafting Policy Language > "Learn from Examples"

<img width="599" alt="screen shot 2016-07-07 at 12 20 51 pm" src="https://cloud.githubusercontent.com/assets/11283576/16660732/a5105856-443d-11e6-9b4e-2ed87f9fa229.png">

These resources, currently listed under "Drafting Policy Language" > "Learn from Examples" should be listed under "Setting Policy Objectives for Broad Appeal":
<img width="908" alt="screen shot 2016-07-07 at 12 20 26 pm" src="https://cloud.githubusercontent.com/assets/11283576/16660746/b052affc-443d-11e6-9c18-17812b9ec4c9.png">

**Comment by jalbertbowden** [comment]
done via https://github.com/sunlightlabs/wwc/commit/1a1e304bc8eadf755e062fd728a9514a70e45750

**Comment by SLarrick** [comment]
Hate to be a buzz kill, but it looks like it is still mixed up on the site http://whatworkscities.sunlightfoundation.com/... (still looks like the above picture)

**Comment by jalbertbowden** [comment]
@SLarrick not a buzz kill at all....you were right. should be fixed now

**Comment by jalbertbowden** [comment]
this is what i see now, referencing @SLarrick's observation today that this was still an issue 
![screen shot 2016-07-28 at 5 21 13 pm](https://cloud.githubusercontent.com/assets/46432/17229924/c8dcc0c0-54e7-11e6-82b5-811ebc4cb33e.png)
if that is not correct, @SLarrick reopen this issue please

**Comment by SLarrick** [comment]
Thanks, @jalbertbowden - looks good!
