### ISSUE TITLE
Add opendatapoliciesdecoded to resource list 

### ISSUE THREAD

**Issue by shazooer** [sunlightlabs/wwc#33]
http://opendatapoliciesdecoded.sunlightfoundation.com/

Under drafting policy language -->learn from examples. 
Alongside compendium, comparison spreadsheet, etc.

**Comment by jalbertbowden** [comment]
this is done https://github.com/sunlightlabs/wwc/commit/18aab0e8e1856976bea8b77fee14957def241d9a
